---
# Étape "Langue" — équivalent de l'écran de langue de l'installateur Windows
region: "Europe"
zone: "Paris"

localeGen: "/etc/locale.gen"
localeConf: "/etc/default/locale"

geoip:
    style: "json"
    url: "https://ipapi.co/json"
    selector: "country_code"
