---
# Étape "Compte local" — équivalent de la création de compte dans le setup Windows
defaultGroups:
    - users
    - lp
    - video
    - network
    - storage
    - wheel
    - audio
    - plugdev
    - netdev

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    sudo
setRootPassword: true

passwordRequirements:
    minLength: 4
    maxLength: -1

allowWeakPasswords: true
allowWeakPasswordsDefault: true

userShell: /bin/bash

presetHostname: psnos

forbidden_names: [ root, admin, guest ]
