---
# Configuration globale de l'installateur PSN_OS
modules-search: [ local ]

instances:
- id: rootfs
  module: unpackfs
  config: unpackfs.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - networkcfg
  - hostname
  - users
  - displaymanager
  - grubcfg
  - bootloader
  - packages
  - shellprocess
  - umount
- show:
  - finished

branding: psnos

prompt-install: false

dont-chroot: false
